routes/web.php
    return view('auth/login');
});

Route::post('/admin/login', 'Account\AuthController@authLogin')->name('login');

// Page admin
Route::prefix('admin')->group(function() {

        
        // Auth View Profile
        Route::get('/profile', 'Account\AuthController@getInfoProfile')->name('profile');
        Route::post('/update-profile', 'Account\AuthController@updateProfile')->name('updateProfile');

        //Change Password
        Route::post('change-password','Account\AuthController@changePassword')->name('changePassword');


        // User
        Route::prefix('user')->group(function() {
            Route::name('user.')->group(function() {
                    Route::get('/','Account\AccountController@listAccount')->name('list');
                    Route::post('/{id}','Account\AccountController@updateUserToStaff')->name('Staff');
            });

        });


         // Product
        Route::prefix('product')->group(function() {


             //Product
             Route::name('product.')->group(function() {
                Route::get('/', 'Product\ProductController@list')->name('list');
                Route::get('/create', 'Product\ProductController@create')->name('created');
                Route::post('/create', 'Product\ProductController@store')->name('stored');
                Route::get('/{id}', 'Product\ProductController@edit')->name('detail');
                Route::post('/{id}/update', 'Product\ProductController@update')->name('updated');
                Route::get('/{id}/deleted', 'Product\ProductController@destroy')->name('deleted');
                });


                //Variant Product
                Route::name('variant.')->group(function() {
                    Route::get('{product_id}/product-variant','Product\ProductVariantController@listProductVariant')
                            ->name('list');
                    Route::get('{product_id}/product-variant', 'Product\ProductVariantController@createProductVariant')
                            ->name('getPageCreate');
                    Route::post('{product_id}/product-variant', 'Product\ProductVariantController@createProductVariant')
                            ->name('created');
                    Route::get('{product_id}/product-variant/{id}', 'Product\ProductVariantController@detailProductVariant')
                            ->name('detail');
                    Route::post('{product_id}/product-variant/{id}', 'Product\ProductVariantController@updateProductVariant')
                            ->name('updated');
                    Route::get('{product_id}/product-variant/{id}', 'Product\ProductVariantController@deleteProductVariant')
                            ->name('deleted');
                });

        
                //Image Product
                Route::name('productimage.')->group(function() {
                    Route::get('{product_id}/product-image','Product\ProductImageController@listProductImage')
                            ->name('listImage');
                    Route::get('{product_id}/product-image/{id}','Product\ProductImageController@detailProductImage')
                            ->name('detail');
                    Route::post('{product_id}/product-image','Product\ProductImageController@uploadImageOfProduct')
                            ->name('uploaded');
                    Route::post('{product_id}/product-image{id}','Product\ProductImageController@updateImageOfProduct')
                            ->name('updated');
                    Route::get('{product_id}/product-image{id}','Product\ProductImageController@deleteImageOfProduct')
                            ->name('deleted');
                });
            
        });

        //Category
        Route::prefix('category')->group(function() {
            Route::name('category.')->group(function() {
                Route::get('/', 'Category\CategoryController@list')->name('list');
                Route::get('/create', 'Category\CategoryController@create')->name('created');
                Route::post('/create', 'Category\CategoryController@store')->name('stored');
                Route::get('/{id}', 'Category\CategoryController@edit')->name('detail');
                Route::post('/{id}/update', 'Category\CategoryController@update')->name('updated');
                Route::get('/{id}/deleted', 'Category\CategoryController@destroy')->name('deleted');
            });

        });


        //Attribute
        Route::prefix('attribute')->group(function() {
            Route::name('attribute.')->group(function() {
                    Route::get('/','Product\AttributeController@list')
                            ->name('list');
                    Route::get('/created','Product\AttributeController@create')
                            ->name('created');
                    Route::post('/created','Product\AttributeController@store')
                            ->name('stored');
                    Route::get('/{id}','Product\AttributeController@edit')
                            ->name('edit');
                    Route::post('/{id}/update','Product\AttributeController@update')
                            ->name('updated');
                    Route::get('/{id}/deleted','Product\AttributeController@destroy')
                            ->name('deleted');
            });
        });

    
        //Attribute Item
        Route::prefix('attribute-item')->group(function() {
            Route::name('attributeitem.')->group(function() {
                    Route::get('/','Product\AttributeItemController@list')
                            ->name('list');
                    Route::get('/create','Product\AttributeItemController@create')
                            ->name('created');
                    Route::post('/create','Product\AttributeItemController@store')
                            ->name('stored');
                    Route::get('/{id}','Product\AttributeItemController@edit')
                            ->name('edit');
                    Route::post('/{id}/update','Product\AttributeItemController@update')
                            ->name('updated');
                    Route::get('/delete/{id}','Product\AttributeItemController@destroy')
                            ->name('deleted');
            });
        });


        // Page Supplier
        Route::prefix('supplier')->group(function() {

            Route::name('supplier.')->group(function() {
                    Route::get('/','Supplier\SupplierController@list')
                            ->name('list');
                    Route::get('/create','Supplier\SupplierController@create')
                            ->name('created');
                    Route::post('create','Supplier\SupplierController@store')
                            ->name('stored');
                    Route::get('/{id}','Supplier\SupplierController@edit')
                            ->name('edit');
                    Route::post('/{id}/update','Supplier\SupplierController@update')
                            ->name('updated');
                    Route::get('/{id}/deleted','Supplier\SupplierController@destroy')
                            ->name('deleted'); 
            });

        });


        // Page DashBoard
        Route::get('dashboard','DashBoardController@dashBoard')->name('dashboard');

        // Page Order 
        Route::prefix('order')->group(function() {

                //Order
                Route::name('order.')->group(function() {
                        Route::get('/','Order\OrderController@list')
                                ->name('list');
                        Route::get('/order-detail','Order\OrderController@detail')
                                ->name('detail'); 
                });

        });


        // Warehouse
        Route::prefix('warehouse')->group(function() {

            Route::name('warehouse.')->group(function() {
                    Route::get('/','Warehouse\WarehouseManagementController@list')
                            ->name('list');
                    Route::get('/{id}','Warehouse\WarehouseManagementController@detail')
                            ->name('detail');
                    Route::post('/{id}','Warehouse\WarehouseManagementController@update')
                            ->name('updated');
            });

        });


        // Import Management
        Route::prefix('import')->group(function() {

            Route::name('import.')->group(function() {
                    Route::get('/','Warehouse\ImportManagementController@list')
                            ->name('list');
                    Route::get('/create','Warehouse\ImportManagementController@create')
                            ->name('create');
                    Route::post('create','Warehouse\ImportManagementController@store')
                            ->name('stored');
                    Route::get('/{id}','Warehouse\ImportManagementController@edit')
                            ->name('edit');
                    Route::post('/{id}','Warehouse\ImportManagementController@update')
                            ->name('updated');
            });

        });


        // Inventory Management
        Route::prefix('inventory')->group(function() {

            Route::name('inventory.')->group(function() {
                    Route::get('/','Warehouse\InventoryManagementController@list')
                            ->name('list');
                    Route::get('/create','Warehouse\InventoryManagementController@create')
                            ->name('created');
                    Route::post('create','Warehouse\InventoryManagementController@store')
                            ->name('stored');
                    Route::get('/{id}','Warehouse\InventoryManagementController@edit')
                            ->name('edit');
                    Route::post('/{id}','Warehouse\InventoryManagementController@update')
                            ->name('updated');
            });

app/Http/Controllers/Product/AttributeController.php
<?php

namespace App\Http\Controllers\Product;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\ProductAttribute;

class AttributeController extends Controller
{
    public function list()
    {
        $attribute = ProductAttribute::all();
        return view('myproduct/attribute/list-attribute',compact('attribute'));
    }

    public function create()
    {
        return view('myproduct/attribute/create-attribute');
    }

    public function store(Request $request)
    {
        $slug = str_slug($request->attribute, '-');
        
        $createAttribute = new ProductAttribute;
        $createAttribute->name = $request->attribute;
        $createAttribute->slug = $slug;

        $createAttribute->save();
        return redirect('admin/attribute')->with('success','Save Category Successfully');
    }

    public function edit($id)
    {
        $detailAttribute = ProductAttribute::find($id);
        return view('myproduct/attribute/edit-attribute',compact('detailAttribute'));
    }

    public function update(Request $request, $id)
    {
        $slug = str_slug($request->attribute, '-');

        $attribute = ProductAttribute::find($id);
        $attribute->name = $request->attribute;
        $attribute->slug = $slug;

        $attribute->save();
        return redirect('admin/attribute');

    }

    public function destroy($id)
    {
        $attribute = ProductAttribute::find($id);
        $attribute->delete();

        return redirect('admin/attribute');
    }
}

resources/views/myproduct/attribute/create-attribute.blade.php
@extends('myproduct/layout-product')

@section('title')
<div class="navbar-wrapper">
    <a class="navbar-brand" href="#">Tạo mới thuộc tính sản phẩm</a>
</div>
@endsection('title')

@section('content')
<!-- Main content  -->
<form action="{{route('attribute.stored')}}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label class="bmd-label-floating">Tên thuộc tính</label>
                <input type="text" class="form-control" name="attribute" id="attribute">
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary pull-right">Tạo thuộc tính</button>
</form>
@endsection('content')

resources/views/myproduct/attribute/edit-attribute.blade.php
@extends('myproduct/layout-product')

@section('title')
<div class="navbar-wrapper">
    <a class="navbar-brand" href="#">Tạo mới thuộc tính sản phẩm</a>
</div>
@endsection('title')

@section('content')
<!-- Main content  -->
<form action="{{route('attribute.updated', ['id' => $detailAttribute->id])}}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label class="bmd-label-floating">Tên thuộc tính</label>
                <input type="text" class="form-control" name="attribute" id="attribute" value="{{$detailAttribute->name}}">
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary pull-right">Tạo thuộc tính</button>
</form>
@endsection('content')

resources/views/myproduct/attribute/list-attribute.blade.php
@extends('myproduct/layout-product')

<!-- Main content  -->
<?php $i=1 ?>
@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="container-fluid">
            <div class="card card-plain">
                <div class="card-header card-header-primary">
                    <h4 class="card-title" style="display:inline">Danh sách các thuộc tính</h4>
                    <a href="{{route('attribute.created')}}" style="float:right;color:white;">
                    Thêm mới
                    <i class="material-icons">add_circle</i>
                    </a>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="datatable" class="table dt-responsive nowrap">
                            <thead class=" text-primary">
                            <th>STT</th>
                            <th>Tên thuộc tính </th>
                            <th>Slug</th>
                            <th>Action</th>
                            </thead>
                            <tbody>
                            @foreach($attribute as $attributes)
                                <tr>
                                    <td><?php echo $i++ ?></td>
                                    <td>{{$attributes->name}}</td>
                                    <td>{{$attributes->slug}}</td>
                                    <td>
                                        <a href="{{route('attribute.edit', ['id' => $attributes->id])}}">
                                            <i class="material-icons">edit</i>
                                        </a>
                                        <a href="{{route('attribute.deleted', ['id' => $attributes->id])}}">
                                            <i class="material-icons">delete</i>
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>      
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection('content')

@section('js')
<script src="{{ asset('assets/libs/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/libs/datatables/dataTables.bootstrap4.js') }}"></script>

<!-- jquery pagination list  -->
<script type="text/javascript">
    $(document).ready(function(){$("#datatable").DataTable({
    language:{
        paginate:{
        previous:"<i class='mdi mdi-chevron-left'>",next:"<i class='mdi mdi-chevron-right'>"
                }
            },drawCallback:function(){
                $(".dataTables_paginate > .pagination").addClass("pagination-rounded")
            }
    });
    });
</script>


@endsection('js')