routes/web.php
    return view('auth/login');
});

Route::post('/admin/login', 'Account\AuthController@authLogin')->name('login');

// Page admin
Route::prefix('admin')->group(function() {

        
        // Auth View Profile
        Route::get('/profile', 'Account\AuthController@getInfoProfile')->name('profile');
        Route::post('/update-profile', 'Account\AuthController@updateProfile')->name('updateProfile');

        //Change Password
        Route::post('change-password','Account\AuthController@changePassword')->name('changePassword');


        // User
        Route::prefix('user')->group(function() {
            Route::name('user.')->group(function() {
                    Route::get('/','Account\AccountController@listAccount')->name('list');
                    Route::post('/{id}','Account\AccountController@updateUserToStaff')->name('Staff');
            });

        });


         // Product
        Route::prefix('product')->group(function() {


             //Product
             Route::name('product.')->group(function() {
                Route::get('/', 'Product\ProductController@list')->name('list');
                Route::get('/create', 'Product\ProductController@create')->name('created');
                Route::post('/create', 'Product\ProductController@store')->name('stored');
                Route::get('/{id}', 'Product\ProductController@edit')->name('detail');
                Route::post('/{id}/update', 'Product\ProductController@update')->name('updated');
                Route::get('/{id}/deleted', 'Product\ProductController@destroy')->name('deleted');
                });


                //Variant Product
                Route::name('variant.')->group(function() {
                    Route::get('{product_id}/product-variant','Product\ProductVariantController@listProductVariant')
                            ->name('list');
                    Route::get('{product_id}/product-variant', 'Product\ProductVariantController@createProductVariant')
                            ->name('getPageCreate');
                    Route::post('{product_id}/product-variant', 'Product\ProductVariantController@createProductVariant')
                            ->name('created');
                    Route::get('{product_id}/product-variant/{id}', 'Product\ProductVariantController@detailProductVariant')
                            ->name('detail');
                    Route::post('{product_id}/product-variant/{id}', 'Product\ProductVariantController@updateProductVariant')
                            ->name('updated');
                    Route::get('{product_id}/product-variant/{id}', 'Product\ProductVariantController@deleteProductVariant')
                            ->name('deleted');
                });

        
                //Image Product
                Route::name('productimage.')->group(function() {
                    Route::get('{product_id}/product-image','Product\ProductImageController@listProductImage')
                            ->name('listImage');
                    Route::get('{product_id}/product-image/{id}','Product\ProductImageController@detailProductImage')
                            ->name('detail');
                    Route::post('{product_id}/product-image','Product\ProductImageController@uploadImageOfProduct')
                            ->name('uploaded');
                    Route::post('{product_id}/product-image{id}','Product\ProductImageController@updateImageOfProduct')
                            ->name('updated');
                    Route::get('{product_id}/product-image{id}','Product\ProductImageController@deleteImageOfProduct')
                            ->name('deleted');
                });
            
        });

        //Category
        Route::prefix('category')->group(function() {
            Route::name('category.')->group(function() {
                Route::get('/', 'Category\CategoryController@list')->name('list');
                Route::get('/create', 'Category\CategoryController@create')->name('created');
                Route::post('/create', 'Category\CategoryController@store')->name('stored');
                Route::get('/{id}', 'Category\CategoryController@edit')->name('detail');
                Route::post('/{id}/update', 'Category\CategoryController@update')->name('updated');
                Route::get('/{id}/deleted', 'Category\CategoryController@destroy')->name('deleted');
            });

        });


        //Attribute
        Route::prefix('attribute')->group(function() {
            Route::name('attribute.')->group(function() {
                    Route::get('/','Product\AttributeController@list')
                            ->name('list');
                    Route::get('/created','Product\AttributeController@create')
                            ->name('created');
                    Route::post('/created','Product\AttributeController@store')
                            ->name('stored');
                    Route::get('/{id}','Product\AttributeController@edit')
                            ->name('edit');
                    Route::post('/{id}/update','Product\AttributeController@update')
                            ->name('updated');
                    Route::get('/{id}/deleted','Product\AttributeController@destroy')
                            ->name('deleted');
            });
        });

    
        //Attribute Item
        Route::prefix('attribute-item')->group(function() {
            Route::name('attributeitem.')->group(function() {
                    Route::get('/','Product\AttributeItemController@list')
                            ->name('list');
                    Route::get('/create','Product\AttributeItemController@create')
                            ->name('created');
                    Route::post('/create','Product\AttributeItemController@store')
                            ->name('stored');
                    Route::get('/{id}','Product\AttributeItemController@edit')
                            ->name('edit');
                    Route::post('/{id}/update','Product\AttributeItemController@update')
                            ->name('updated');
                    Route::get('/delete/{id}','Product\AttributeItemController@destroy')
                            ->name('deleted');
            });
        });


        // Page Supplier
        Route::prefix('supplier')->group(function() {

            Route::name('supplier.')->group(function() {
                    Route::get('/','Supplier\SupplierController@list')
                            ->name('list');
                    Route::get('/create','Supplier\SupplierController@create')
                            ->name('created');
                    Route::post('create','Supplier\SupplierController@store')
                            ->name('stored');
                    Route::get('/{id}','Supplier\SupplierController@edit')
                            ->name('edit');
                    Route::post('/{id}/update','Supplier\SupplierController@update')
                            ->name('updated');
                    Route::get('/{id}/deleted','Supplier\SupplierController@destroy')
                            ->name('deleted'); 
            });

        });


        // Page DashBoard
        Route::get('dashboard','DashBoardController@dashBoard')->name('dashboard');

        // Page Order 
        Route::prefix('order')->group(function() {

                //Order
                Route::name('order.')->group(function() {
                        Route::get('/','Order\OrderController@list')
                                ->name('list');
                        Route::get('/order-detail','Order\OrderController@detail')
                                ->name('detail'); 
                });

        });


        // Warehouse
        Route::prefix('warehouse')->group(function() {

            Route::name('warehouse.')->group(function() {
                    Route::get('/','Warehouse\WarehouseManagementController@list')
                            ->name('list');
                    Route::get('/{id}','Warehouse\WarehouseManagementController@detail')
                            ->name('detail');
                    Route::post('/{id}','Warehouse\WarehouseManagementController@update')
                            ->name('updated');
            });

        });


        // Import Management
        Route::prefix('import')->group(function() {

            Route::name('import.')->group(function() {
                    Route::get('/','Warehouse\ImportManagementController@list')
                            ->name('list');
                    Route::get('/create','Warehouse\ImportManagementController@create')
                            ->name('create');
                    Route::post('create','Warehouse\ImportManagementController@store')
                            ->name('stored');
                    Route::get('/{id}','Warehouse\ImportManagementController@edit')
                            ->name('edit');
                    Route::post('/{id}','Warehouse\ImportManagementController@update')
                            ->name('updated');
            });

        });


        // Inventory Management
        Route::prefix('inventory')->group(function() {

            Route::name('inventory.')->group(function() {
                    Route::get('/','Warehouse\InventoryManagementController@list')
                            ->name('list');
                    Route::get('/create','Warehouse\InventoryManagementController@create')
                            ->name('created');
                    Route::post('create','Warehouse\InventoryManagementController@store')
                            ->name('stored');
                    Route::get('/{id}','Warehouse\InventoryManagementController@edit')
                            ->name('edit');
                    Route::post('/{id}','Warehouse\InventoryManagementController@update')
                            ->name('updated');
            });

app/Supplier.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Supplier extends Model
{
    protected $table = 'suppliers';

    use SoftDeletes;
}

app/Http/Controllers/Supplier/SupplierController.php
<?php

namespace App\Http\Controllers\Supplier;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Supplier;

class SupplierController extends Controller
{

    public function list()
    {
        $supplier = Supplier::all();
        return view('supplier/list-supplier',compact('supplier'));
    }

    public function create()
    {
        return view('supplier/create-supplier');
    }

    public function store(Request $request)
    {
        $createSupplier = new Supplier;
        $createSupplier->name = $request->suppliername;
        $createSupplier->description = $request->description;
        $createSupplier->phone_number = $request->hotline;
        $createSupplier->address = $request->address;

        $createSupplier->save();
        return redirect('admin/supplier')->with('success','Save Category Successfully');
    }

    public function edit($id)
    {
        $detailSupplier = Supplier::find($id);
        return view('supplier/edit-supplier',compact('detailSupplier'));
    }

    public function update(Request $request, $id)
    {
        $supplier = Supplier::find($id);
        $supplier->name = $request->suppliername;
        $supplier->description = $request->description;
        $supplier->phone_number = $request->hotline;
        $supplier->address = $request->address;

        $supplier->save();
        return redirect('admin/supplier');

    }

    public function destroy($id)
    {
        $supplier = Supplier::find($id);
        $supplier->delete();

        return redirect('admin/supplier');
    }
}

resources/views/supplier/create-supplier.blade.php
@extends('supplier/layout-supplier')

@section('title')
<div class="navbar-wrapper">
    <a class="navbar-brand" href="#">Tạo mới nhà cung cấp</a>
</div>
@endsection('title')

@section('content')
<!-- Main content  -->
<form action="{{route('supplier.updated')}}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label class="bmd-label-floating">Tên nhà cung cấp</label>
                <input type="text" class="form-control" name="suppliername" id="suppliername">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
        <div class="form-group">
            <label class="bmd-label-floating">Mô tả nhà cung cấp</label>
            <input type="textarea" class="form-control" name="description" id="description">
        </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
        <div class="form-group">
            <label class="bmd-label-floating">Hotline</label>
            <input type="textarea" class="form-control" name="hotline" id="hotline">
        </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
        <div class="form-group">
            <label class="bmd-label-floating">Địa chỉ</label>
            <input type="textarea" class="form-control" name="address" id="address">
        </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary pull-right">Tạo mới</button>
</form>
@endsection('content')

resources/views/supplier/edit-supplier.blade.php
@extends('supplier/layout-supplier')

@section('title')
<div class="navbar-wrapper">
    <a class="navbar-brand" href="#">Tạo mới nhà cung cấp</a>
</div>
@endsection('title')

@section('content')
<!-- Main content  -->
<form action="{{route('supplier.updated', ['id' => $detailSupplier->id])}}" method="POST" enctype="multipart/form-data">
    @csrf
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label class="bmd-label-floating">Tên nhà cung cấp</label>
                <input type="text" class="form-control" name="suppliername" id="suppliername" value="{{$detailSupplier->name}}">
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
        <div class="form-group">
            <label class="bmd-label-floating">Mô tả nhà cung cấp</label>
            <input type="textarea" class="form-control" name="description" id="description" value="{{$detailSupplier->description}}">
        </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
        <div class="form-group">
            <label class="bmd-label-floating">Hotline</label>
            <input type="textarea" class="form-control" name="hotline" id="hotline" value="{{$detailSupplier->phone_number}}">
        </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
        <div class="form-group">
            <label class="bmd-label-floating">Địa chỉ</label>
            <input type="textarea" class="form-control" name="address" id="address" value="{{$detailSupplier->address}}">
        </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary pull-right">Cập nhật</button>
</form>
@endsection('content')

resources/views/supplier/layout-supplier.blade.php
@extends('layout')

<!-- Title of Table -->
@section('title')
<div class="navbar-wrapper">
    <a class="navbar-brand" href="#">Nhà cung cấp</a>
</div>
@endsection('title')

<!-- Layout Menu -->
@section('menu')
    <div class="sidebar-wrapper">
      <ul class="nav">
        <li class="nav-item  ">
          <a class="nav-link" href="#">
            <i class="material-icons">dashboard</i>
            <p>Quản lý</p>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">
            <i class="material-icons">person</i>
            <p>Tài khoản</p>
          </a>
        </li>
        <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown" data-toggle="dropdown">
                <i class="material-icons">list</i>
                <span class="caret"></span>
                <p>Sản phẩm</p>
            </a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                <li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('product.list')}}">Danh sách sản phẩm</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('attribute.list')}}">Thuộc tính sản phẩm</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('attributeitem.list')}}">Giá trị thuộc tính</a></li>
                </ul>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{{route('supplier.list')}}">
            <i class="material-icons">store</i>
            <p>Nhà cung cấp</p>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{route('category.list')}}">
            <i class="material-icons">category</i>
            <p>Loại sản phẩm</p>
          </a>
        </li>
        <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown" data-toggle="dropdown">
                <i class="material-icons">house</i>
                <span class="caret"></span>
                <p>Quản lý kho</p>
            </a>
                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('import.list')}}">Nhập hàng</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('inventory.list')}}">Xuất hàng</a></li>
                    <li role="presentation"><a role="menuitem" tabindex="-1" href="{{route('warehouse.list')}}">Hàng tồn</a></li>
                </ul>
        </li>
        <li class="nav-item ">
          <a class="nav-link" href="{{route('order.list')}}">
            <i class="material-icons">receipt</i>
            <p>Danh sách hóa đơn</p>
          </a>
        </li>
      </ul>
    </div>
@endsection('menu')

resources/views/supplier/list-supplier.blade.php
@extends('supplier/layout-supplier')

<!-- Main content  -->
<?php $i=1 ?>
@section('content')
<div class="content">
    <div class="container-fluid">
        <div class="container-fluid">
            <div class="card card-plain">
                <div class="card-header card-header-primary">
                    <h4 class="card-title" style="display:inline">Nhà cung cấp</h4>
                    <a href="{{route('supplier.created')}}" style="float:right;color:white;">
                    Thêm mới
                    <i class="material-icons">add_circle</i>
                    </a>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table id="datatable" class="table dt-responsive nowrap">
                            <thead class=" text-primary">
                            <th>STT</th>
                            <th>Tên nhà cung cấp</th>
                            <th>Số điện thoại</th>
                            <th>Địa chỉ</th>
                            <th>Action</th>
                            </thead>
                            <tbody>
                            @foreach($supplier as $suppliers)
                                <tr>
                                    <td><?php echo $i++ ?></td>
                                    <td>{{$suppliers->name}}</td>
                                    <td>{{$suppliers->phone_number}}</td>
                                    <td>{{$suppliers->address}}</td>
                                    <td>
                                    <a href="{{route('supplier.edit', ['id' => $suppliers->id])}}">
                                        <i class="material-icons">edit</i>
                                    </a>
                                    <a href="{{route('supplier.deleted', ['id' => $suppliers->id])}}">
                                        <i class="material-icons">delete</i>
                                    </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>      
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection('content')

@section('js')
<script src="{{ asset('assets/libs/datatables/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/libs/datatables/dataTables.bootstrap4.js') }}"></script>

<!-- jquery pagination list  -->
<script type="text/javascript">
    $(document).ready(function(){$("#datatable").DataTable({
    language:{
        paginate:{
        previous:"<i class='mdi mdi-chevron-left'>",next:"<i class='mdi mdi-chevron-right'>"
                }
            },drawCallback:function(){
                $(".dataTables_paginate > .pagination").addClass("pagination-rounded")
            }
    });
    });
</script>
@endsection('js')